php:
  image: php:7.4.7-apache
  volumes:
   - .:/var/www/html
  ports:
   - "80:80"
   - "443:443"
django:
  build: .
  command: python manage.py runserver 0.0.0.0:8000
  volumes:
   - .:/var/www/html
  ports:
   - "8000:8000"
